name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  ultra-next:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ ultranext ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'  # Explicitly use Node.js 20 for checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7 # Correct format for SSH action
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/var/www/html/test-front/.git" ]; then
            git clone https://github.com/ilqar96/promptopia.git /var/www/html/test-front
            fi
            
            cd /var/www/html/test-front
            git pull origin main
            npm install
            npm run build
            pm2 restart ultrafix-front-v1
